apiVersion: v2
name: alcide-advisor-job
description: Alcide Advisor Job
keywords:
  - security
  - vulnerability scan
  - guardrails
  - gitops
type: application
version: 1.0.0
appVersion: 2.12.0
home: https://www.alcide.io
icon: https://www.alcide.io/wp-content/uploads/2020/01/advisor@3x.png
sources:
- https://github.com/alcideio/advisor
- https://github.com/alcideio/pipeline
maintainers:
- email: gadi@alcide.io
  name: gadinaor
