{
 "title": "Alcide Kubernetes Advisor",
 "tags": [
  "security",
  "alcide"
 ],
 "time": { "from": "now/w", "to": "now" },
 "panels": [
  {
   "title": "Critical",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(alcide_advisor_total_count_by_severity{severity=\"critical\"}) without (pod)"
    }
   ]
  },
  {
   "title": "High",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(alcide_advisor_total_count_by_severity{severity=\"high\"}) without (pod)"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(alcide_advisor_total_count_by_severity{severity=\"low\"}) without (pod)"
    }
   ]
  },
  {
   "title": "Low",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(alcide_advisor_total_count_by_severity{severity=\"low\"}) without (pod)"
    }
   ]
  },
  {
   "title": "Severity Totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(alcide_advisor_total_count_by_severity{severity=~\"critical|high|medium\"}) without (pod)",
     "legendFormat": "Severity: {{ severity}}"
    }
   ]
  },
  {
   "title": "(Critical & High) Severity Count Per Resource",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(alcide_advisor_resource_severity_count{severity=~\"critical\"} > 0) without (pod)\n",
     "legendFormat": "Critical | {{k8s_apikind}}.{{k8s_apigroup}}/{{k8s_apiversion}}  |  {{k8s_name}}/{{ k8s_namespace}}"
    },
    {
     "expr": "max(alcide_advisor_resource_severity_count{severity=~\"high\"} > 0) without (pod)\n",
     "legendFormat": "High |  {{k8s_apikind}}.{{k8s_apigroup}}/{{k8s_apiversion}}  |  {{k8s_name}}/{{ k8s_namespace}}"
    }
   ]
  },
  {
   "title": "Findings Per Check",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(alcide_advisor_total_by_check) without (pod)",
     "legendFormat": "{{ check_title}}"
    }
   ]
  }
 ]
}