{{ if ne .Values.alcide.advisorProfileFile "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alcide-advisor.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
data:
  profile.advisor: |
{{ .Files.Get .Values.alcide.advisorProfileFile  | indent 4 -}}
{{ end }}
