---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "alcide-advisor.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "alcide-advisor.fullname" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["proxy"]    
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "alcide-advisor.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "alcide-advisor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "alcide-advisor.fullname" . }}
    namespace: {{ .Release.Namespace }}
