apiVersion: v1
kind: Namespace
metadata:
  name: alcide-advisor
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: advisorjob
  namespace: alcide-advisor
spec:
  schedule: "*/1 * * * *"

  # Keep the last run
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  # Concurrency is not required
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: advisor
            run: alcide-advisor
            version: dev
        spec:
          initContainers:
            - name: vault-agent-auth
              args:
                - agent
                - -config=/etc/vault/vault-agent-config.hcl
              env:
                - name: VAULT_ADDR
                  value: http://vault.demo:8200
                - name: VAULT_AGENT_ADDR
                  value: http://localhost:8100
              image: vault
              imagePullPolicy: IfNotPresent
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:            
                - mountPath: /etc/vault
                  name: config
                - mountPath: /home/vault
                  name: vault-token
          containers:
            - name: advisor
              #
              # For debugging Vault injection ... going away soooooon
              #
              # imagePullPolicy: IfNotPresent
              # image: nginx
              # command: ["nginx", "-g", "daemon off;"]
              image: alcidelabs/advisor:2.10.1-vault
              imagePullPolicy: Always
              args:
                - --eula-sign
                - validate
                - cluster
                - --inCluster
                #
                # Slack Export
                #                              
                # - --slack-channel
                # - "@someuser"
                #
                # Use Alcide Cloud managed scan profile
                #
                # - --profile-id
                # - 12345-6789-1234-aaaa-1234567678
                # - --organization
                # - myaccount
                # - --alcide-api-server
                # - myaccount.cloud.alcide.io
                #
                # S3 Export
                #
                #- --s3-export-url
                #- "s3://mybucket/subdir?region=us-west-2"
                #
                # Load Secrets from file
                #
                - --config 
                - /home/vault/secrets/alcide-advisor.yaml
                #- --debug
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                runAsUser: 10001
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /home/vault
                  name: vault-token                
          serviceAccountName: alcide-advisor
          volumes:         
            - emptyDir:
                medium: Memory
              name: vault-token
            - configMap:
                defaultMode: 420
                items:
                  - key: vault-agent-config.hcl
                    path: vault-agent-config.hcl
                name: vault-agent-config
              name: config
          restartPolicy: OnFailure
