---
# Source: alcide-advisor-cronjob/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alcide-advisor
  namespace: alcide-advisor
---
# Source: alcide-advisor-cronjob/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: alcide-advisor
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["proxy"]    
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
# Source: alcide-advisor-cronjob/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alcide-advisor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alcide-advisor
subjects:
  - kind: ServiceAccount
    name: alcide-advisor
    namespace: alcide-advisor
---
