name: Release Draft (from master)

on:
  push:
    branches:
      - xxxxxxxxx

jobs:
  tag-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  release-draft:
    name: Release Me
    runs-on: ubuntu-latest
    needs: tag-master
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_REGISTRY_URL: "docker.pkg.github.com"  
      DOCKER_IMAGE: kruzio/kube-dialer
      REPOSITORY: kruzio/kube-dialer/dialer  

    steps:
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
