name: Test Alcide Advisor Helm Charts

on:
  push:
    branches:
      - '*'

jobs:
  installation-tests:
    name: Alcide Advisor Install Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Launch Cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          version: v0.7.0
          name: kruzer
          node_image: kindest/node:v1.16.4
          wait: 5m
          install_local_path_provisioner: true

      - name: Install Helm 3
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 
          chmod 700 get_helm.sh
          ./get_helm.sh          

      - name: Prepare Namespaces 
        run: |
          kubectl create ns alcide-advisor
          

      - name: Test Advisor CronJob 
        run: |
          echo "Installing Alcide Advisor CronJob with Exported Profile"
          helm upgrade -i -n alcide-advisor --wait  exportedprofile deploy/charts/alcide-advisor-cronjob          

          echo "Installing Alcide Advisor CronJob"
          helm upgrade -i -n alcide-advisor --wait  scan deploy/charts/alcide-advisor-cronjob \
              --set alcide.advisorProfileFile=advisor-profiles/alcide-kubernetes-assessment.advisor 
 
          kubectl -n alcide-advisor get cronjobs
          kubectl -n alcide-advisor describe cronjobs

      - name: Test Advisor Job 
        run: |

          echo "Installing Alcide Advisor Job with Exported Profile"
          helm upgrade -i -n alcide-advisor --wait  scanjob deploy/charts/alcide-advisor-job          

          echo "Installing Alcide Advisor"
          helm upgrade -i -n alcide-advisor --wait  argocd deploy/charts/alcide-advisor-cronjob \
              --set alcide.advisorProfileFile=advisor-profiles/alcide-kubernetes-assessment.advisor 
 
          kubectl -n alcide-advisor get jobs
          kubectl -n alcide-advisor describe jobs

